cd "../../../playwright_files/playwright-node-files/gloves/other/men"
node "scrap_men-other.js"
cd "../../../../../scrape-and-ag/web-src-scraping/gloves/other/men"
node "ocr_men-other.js"
cd "../../../../data-ag/gloves/other/men"
node "analyze_men-other.js"
cd "../../../../../scrape-and-ag/scripts/gloves"