cd "../../../playwright_files/playwright-node-files/gloves/right/women"
node "scrape_women-right.js"
cd "../../../../../scrape-and-ag/ocr/gloves/right/women"
node "ocr_women-right.js"
cd "../../../../data-ag/gloves/right/women"
node "analyze_women-right.js"
cd "../../../../../scrape-and-ag/scripts/gloves"