cd "../../../playwright_files/playwright-node-files/clubs/putters"
node "scrape_putters.js"
cd "../../../../scrape-and-ag/ocr/clubs/putters"
node "ocr_putters.js"
cd "../../../data-ag/clubs/putters/"
node "analyze_putters.js"
cd "../../../../scrape-and-ag/scripts/clubs"